plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator
  - kramdown-parser-gfm

page_gen_dirs: true

page_gen:
- data: projects
  template: project
  dir: ''
  name_expr: "record['name'].gsub(' ', '-').downcase"
  title: name
  filter_condition: "record['type'] == 'Research'"
- data: projects
  template: project
  dir: ''
  name_expr: "record['name'].gsub(' ', '-').downcase"
  title: name
  filter_condition: "record['type'] == 'Experiments'"
- data: projects
  template: project
  dir: ''
  name_expr: "record['name'].gsub(' ', '-').downcase"
  title: name
  filter_condition: "record['type'] == 'Design'"
- data: projects
  template: project
  dir: ''
  name_expr: "record['name'].gsub(' ', '-').downcase"
  title: name
  filter_condition: "record['type'] == 'Art'"

sass:
  style: compressed
